export const enum ETaskStatus {
  NOTSEEN = "NOTSEEN",
  INPROGRESS = "INPROGRESS",
  POSTPONED = "POSTPONED",
  DONE = "DONE",
  ABANDONED = "ABANDONED",
}

export enum EDocumentStatus {
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
  SEEN = "SEEN",
  INPROGRESS = "INPROGRESS",
}
